name: Jar Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble Release
        run: ./gradlew :Parser:assembleRelease

      - name: Export JAR
        run: ./gradlew :Parser:exportJar

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: Parser/build/libs/*.jar
